### ISSUE TITLE
Task Force feedback on Button has acc name [97a4e1]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1077]
https://act-rules.github.io/rules/97a4e1

## Sailesh Panchang

1. [x] I believe an element with a semantic role of button is more robustly tested by a rule for SC 1.1.1 that requires validation of the purpose conveyed by the text equivalent. Essentially for a native HTML button it is the button content or value or title.
    The mere presence of an accessible name may not be satisfactory. It still needs to pass SC 1.1.1. Even a custom element with role=button will need to pass SC 1.1.1.  Maybe this rule should reference this info and SC 1.1.1 and a rule that supports that.

**Answer**: The current mapping has consensus from the CG. AGWG has been asked to weigh in. If they conclude otherwise we will update, but I propose we keep this "as is" until AG comes with another answer.

2. [x] SC 4.1.2 can also kick in to test the state of a button when it is important in certain situations, like pressed or not.

**Answer**: Possibly, but this is outside the scope of this rule.

3. [x] Is there a need for this assumption: "The rule assumes that all buttons are user interface components as defined by WCAG 2".
    Essentially this rule applies to elements that are confirmed button elements.
If something that is exposed as a button is not one, then the role assigned to the element is incorrect. An element with a semantic role of a button is meant to be an UIC.

**Answer**: Not all buttons are UICs. For example a spinbutton has an up and down button embedded in it. Those up and down buttons aren't considered their own component, they are part of the spinbutton, and so don't need their own accessible name. This assumption captures those types of situations. We can improve the assumption text to make this clearer though.

## Maureen Kraft

- [ ] Applicability is not clear. "The rule applies to elements that are included in the accessibility tree with the semantic role of button, except for input elements of type="image"." It is not clear if this rule applies or does not apply to input elements of type="image". Would be better to state "The rule applies to elements that are included in the accessibility tree with the semantic role of button. This rule does not apply to input elements of type="image"." Github issue opened, https://github.com/act-rules/act-rules.github.io/issues/1061

**Anwer:** This is being addressed in #1121.

- [ ] Passed Example 1 should state why the element is accessible as opposed to "Regular button". Restate to something like, "Button element name is the accessible name." Opened Github issue https://github.com/act-rules/act-rules.github.io/issues/1062

- [ ] Update link to HTML Core Mappings to button section. https://github.com/act-rules/act-rules.github.io/issues/1063

- [ ] Text at top of window overwrites rule text making it difficult to read, "A Community Group of theWorld Wide Web Consortium. Developed with the support of the EU-funded WAI-Tools Project."
https://github.com/act-rules/act-rules.github.io/issues/1064

## Detlev Fischer	

- [ ] Should there be an example with disabled state? maybe not necessary...

## Mary Jo Mueller

- [ ] Trusted tester has implementation results - see issue 1047. So the question I have is, as we keep moving along will we have to have the task force's additional review and approval as well as the AG WG review and approval any time we have a new implementation to add? Or can we simply update published rules with the implementation info?

- [ ] Should there also be a test case for a div with ARIA role="button"? What about a link with an ARIA role="button"?

## Trevor Bostic	

- [ ] I think there is some duplication that could be reduced. Failed example 1 and 3 both have the value attribute in a button, but I think it is clearer to only have the value attribute in example 1. Similarly, inapplicable examples 2 and 4 both revolve around the aria-hidden attribute. I am wondering if inapplicable example 2 should be removed. I think it might only cause more confusion since it not being visible really has no effect on it being inapplicable (though perhaps its good with symmetry for the passed and failed examples). .

## Wilco Fiers

- [ ] Inapplicable example 2 is problematic. That button is still focusable, this may not fail the rule, but arguably this fails 4.1.2.

**Comment by jkodu** [comment]
@WilcoFiers should this be an Agenda Item?

**Comment by jkodu** [comment]
Duplicate issue - https://github.com/w3c/wcag-act/issues/427
