### ISSUE TITLE
Automated Implementation Mapping

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#486]
**Problem:** To test an implementation, we manually create a many-to-many mapping, from ACT-R rules to an implementation's ruleset. This is labour intensive and error prone, especially over longer term. Manually maintaining a mapping also makes it impossible to do any testing when a mapping hasn't yet been defined.

**Solution:** We create a rough mapping based on success criteria, and refine it based on test results. Example:

Let's say we have a rule for WCAG SC 1.3.1 with an ID of "abc123". It has 2 passed, 2 failed, and 2 inapplicable examples. To test if an automated tool has implemented this rule, we run all its rules for SC 1.3.1 on the 6 examples. After we did this, it runs results for 3 rules, called `foo`, `bar` and `baz`, which have the following outcomes:

| Test case | foo  | bar  | baz  | 
|-----------|------|------|------|
| Pass_TC-1 | pass | N/A  | N/A  |
| Pass_TC-2 | N/A  | pass | pass |
| Fail_TC-1 | fail | N/A  | N/A  |
| Fail_TC-2 | pass | fail | pass |
| N/A_TC-1  | pass | N/A  | N/A  |
| N/A_TC-2  | N/A  | pass | N/A  |

Based on those results alone, we can infer how `foo`, `bar`, and `baz`, map to "abc123":

1. `baz` is **not** an implementation of "abc123" because it does not return `failed` for any of the `failed` test cases.
2. Neither `foo` nor `bar` are *complete* implementations of "abc123", because neither of them failed both failure test cases.
3. The combined set of `foo` and `bar` are a complete implementation of "abc123", because together all failure test cases are failed by this set of rules.
4. The ruleset of `foo` + `bar` is a *correct* implementation of "abc123", because neither of these rules fail any of the passed or inapplicable test cases
5. The ruleset of `foo` + `bar` is a fully automated implementation of "abc123", because neither of them returned "incomplete" on any of the test cases for this rule. 

## TODO

- [ ] Define the different "types" of implementations
- [ ] Work out how to deal with mapping to multiple criteria
- [ ] Work out how to deal with "satisfying" rules (e.g. rules that can satisfy an SC)
- [ ] Figure out what to do with overlapping results (e.g. multiple possibilities for a complete set - does that matter?)
- [ ] Describe how handle multiple outcomes from a single rule, on a single test case
- [ ] Figure out if this requires updating test cases (probably, some passes / inapplicables are failures to the SC they map to)
- [ ] Create a script to automatically produce a mapping

**Comment by jkodu** [comment]
This is how implementations are resolved in the site now. So closing this.
